name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-latest] # macos-latest
        target: [x32_64] # x86_32
        cc: [gcc, clang]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Install dependencies (ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install -y gcc-multilib bmake libc6-dev-i386

#      - name: Install dependencies (macos)
#        if: startsWith(matrix.os, 'macos')
#        run: brew install gcc bmake

      - name: Build
        run: bmake CC=${{ matrix.cc }} TARGETARCH=${{ matrix.target }}
