name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04] # macos-latest
        target: [x32_64] # x86_32
        cc: [gcc, clang]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Install dependencies (ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib bmake libc6-dev-i386

#      - name: Install dependencies (macos)
#        if: startsWith(matrix.os, 'macos')
#        run: brew install gcc bmake

      - name: Build
        run: bmake -r CC=${{ matrix.cc }} TARGETARCH=${{ matrix.target }} -DALLARCH
